### ISSUE TITLE
Crash about Wii Remote and Nunchuck

### ISSUE THREAD

**Issue by BenjaminTheHedgefox** [Clownacy/Sonic-Mania-Decompilation#1]
I found this as I wanted to swap from Wii Remote and Nunchuk to Wii Classic Controller, I disconnected the Nunchuk on the title screen and "beeeeeeeeeeeeeeeeeeeep". This was before Sonic was visible, by the way.

**Comment by Clownacy** [comment]
Hopefully, this has been fixed in [v0.7](https://github.com/Clownacy/Sonic-Mania-Decompilation/releases/tag/v0.7) ([this commit](https://github.com/Clownacy/RSDKv5-Decompilation/commit/37eafb56a3806b5b04ec9988cb2513ae59f5878d)).

**Comment by Clownacy** [comment]
If this crash is still happening, feel free to reopen this issue.
