### ISSUE TITLE
How to I open the dev menu?

### ISSUE THREAD

**Issue by greg065** [Clownacy/Sonic-Mania-Decompilation#12]
I need to enable a mod, called Sonic Mania Competition Plus, don't know where else to ask.
The mod is this one [https://gamebanana.com/mods/47851](url)

It looks like I need to enable it in the dev menu to work, but I tried pressing every key and it doesn't show up, I guess I need a combination of different buttons. I also can't tell if the mod was placed in the mods folder correctly, since I can't check...

Also the game frezzes when you press the Home menu. Not much of an issue but wanted to bring that up.

**Comment by Clownacy** [comment]
The dev menu is opened by pressing the top left of the touchscreen.
