### ISSUE TITLE
Screen flickering badly during FMV scene while game is in dimmed mode

### ISSUE THREAD

**Issue by vaguerant** [Clownacy/Sonic-Mania-Decompilation#2]
If you leave the game on the title screen for whatever period of time it takes for the screen to fade out, the FMVs will start flickering between dimmed and undimmed rapidly. This specifically happens toward the end of the opening FMV, starting from the part where Sonic is in Studiopolis Zone and gets surprised from behind by an Eggrobo until the end of the FMV.

**Additional notes:**
- issue resolves at the end of the FMV, but recurs the next time the cutscene reaches that point
- occurs with either FMV version (the two soundtracks, no idea if these are actually different files or just alternate sound channels on one file, etc.)
- visible on both TV and GamePad
- likely to be an epilepsy hazard

Testing on release build v0.8.

**EDIT:** My camera doesn't really capture the severity of the issue due to the speed of the flickering, but here's an attempt (**epilepsy warning**):

https://user-images.githubusercontent.com/5259025/191200910-8c1d9981-3adb-4a44-86de-1de2cf53dfdc.mp4

**Comment by Clownacy** [comment]
That's hopefully been fixed in [this commit](https://github.com/Clownacy/SDL/commit/93993a78d25d8130746289cf1b96a1d254b36b5e).

**Comment by vaguerant** [comment]
Confirming I can no longer reproduce on v1.0. Nice work!

**Comment by Clownacy** [comment]
Thanks!
